<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>

    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>

    <PackageId>SmartLogger</PackageId>
    
    <!-- 
      Default version for local builds.
      In CI/CD, this value is overridden by the Git tag (via /p:Version).
    -->
    <Version Condition="'$(Version)' == ''">0.0.0-dev</Version>
    
    <Authors>Srimani</Authors>

    <Description>
      Hey Reader, Let me be clear... SmartLogger is not about replacing existing logging frameworks. I built it to challenge my own understanding of system design: to find out 𝒊𝒇 𝒕𝒉𝒆 𝒊𝒅𝒆𝒂𝒔 𝒕𝒉𝒂𝒕 𝒎𝒂𝒌𝒆 𝒔𝒆𝒏𝒔𝒆 𝒐𝒏 𝒑𝒂𝒑𝒆𝒓 𝒔𝒕𝒊𝒍𝒍 𝒎𝒂𝒌𝒆 𝒔𝒆𝒏𝒔𝒆 𝒘𝒉𝒆𝒏 𝒕𝒉𝒆 𝒔𝒚𝒔𝒕𝒆𝒎 𝒊𝒔 𝒖𝒏𝒅𝒆𝒓 𝒑𝒓𝒆𝒔𝒔𝒖𝒓𝒆.
    </Description>

    <PackageTags>
      logging;logger;dotnet;observability;correlation-id;structured-logging;
      runtime-configuration;thread-safe;async;diagnostics;monitoring
    </PackageTags>

    <RepositoryUrl>https://github.com/srimani-ravikumar/SmartLogger</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageProjectUrl>https://github.com/srimani-ravikumar/SmartLogger</PackageProjectUrl>

    <PackageLicenseExpression>MIT</PackageLicenseExpression>

    <PackageIcon>Icon.png</PackageIcon>

    <PackageReadmeFile>package-readme.md</PackageReadmeFile>
    
  </PropertyGroup>

  <ItemGroup>
    <None Include="Assets/Icon.png" Pack="true" PackagePath="\" />

    <None Include="../../docs/client/package-readme.md" Pack="true" PackagePath="\" />

    <InternalsVisibleTo Include="SmartLogger.Tests" />
  </ItemGroup>

</Project>